/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mLHfBffLGoBvgRdGyiqscP

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariants_9X38UEjBR5 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 9X38U-EjB-R5/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariants_9X38UEjBR5
});
